import re
from pathlib import Path
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable, Image as RLImage
from reportlab.pdfgen import canvas

class NumberedCanvas(canvas.Canvas):
    """Custom canvas that adds running header and 'Page X of Y' footer."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_number(num_pages)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)

    def draw_page_number(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 9)
        self.setFillColor(colors.HexColor("#718096"))
        
        # Header (pages after page 1)
        if self._pageNumber > 1:
            self.drawString(54, 11 * 72 - 36, "AI Student Study Notes")
            self.setStrokeColor(colors.HexColor("#E2E8F0"))
            self.setLineWidth(0.5)
            self.line(54, 11 * 72 - 42, 8.5 * 72 - 54, 11 * 72 - 42)

        # Footer
        text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(8.5 * 72 - 54, 36, text)
        self.drawString(54, 36, "Generated by WhatsApp AI Study Assistant")
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(54, 46, 8.5 * 72 - 54, 46)
        self.restoreState()


def _sanitize_for_reportlab(text: str) -> str:
    """Escape XML entities and safely convert markdown bold/italic/code to ReportLab tags."""
    if not text:
        return ""

    # Clean academic tags for PDF printing
    text = re.sub(r"\[HL:\s*(?:yellow|green|pink)\s*\|\s*([^\]]+)\]", r"<b>\1</b>", text)
    text = re.sub(r"\[STICKY_THINK:\s*([^\]]+)\]", r"<b>[THINK]</b> <i>\1</i>", text)
    text = re.sub(r"\[STICKY_REMEMBER:\s*([^\]]+)\]", r"<b>[REMEMBER]</b> <i>\1</i>", text)
    text = re.sub(r"\[STICKY_EXAM:\s*([^\]]+)\]", r"<b>[EXAM FOCUS]</b> <i>\1</i>", text)
    text = re.sub(r"\[STICKY_FACT:\s*([^\]]+)\]", r"<b>[KEY FACT]</b> <i>\1</i>", text)
    text = re.sub(r"\[MEMORY_TRICK:\s*([^\]]+)\]", r"<b>[MEMORY TRICK]</b> <i>\1</i>", text)

    # Protect inline code from asterisk/italic collisions
    code_tokens = []
    def save_code(match):
        idx = len(code_tokens)
        code_tokens.append(match.group(1))
        return f"__CODE_TOKEN_{idx}__"

    text = re.sub(r"`([^`]+)`", save_code, text)

    # Escape bare & and XML brackets
    text = re.sub(r"&(?!(amp|lt|gt|quot|apos);)", "&amp;", text)
    text = text.replace("<", "&lt;").replace(">", "&gt;")
    
    # Convert markdown bold **text** -> <b>text</b>
    text = re.sub(r"\*\*([^*]+)\*\*", r"<b>\1</b>", text)
    # Convert markdown italic *text* (word boundary or space aware to avoid C pointers like *ptr)
    text = re.sub(r"(?<!\w)\*([^*]+)\*(?!\w)", r"<i>\1</i>", text)
    
    # Restore code tokens with Courier font
    for idx, code_content in enumerate(code_tokens):
        safe_code = code_content.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        text = text.replace(f"__CODE_TOKEN_{idx}__", f'<font face="Courier" color="#1A365D">{safe_code}</font>')

    return text


def generate_notes_pdf(
    topic: str,
    markdown_content: str,
    output_path: str | Path,
    diagram_image_path: str | Path | None = None
) -> str:
    """Generate an academic study guide PDF from markdown notes."""
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=54
    )

    styles = getSampleStyleSheet()

    # Custom typography styles
    primary_color = colors.HexColor("#1A365D")
    secondary_color = colors.HexColor("#2B6CB0")
    text_color = colors.HexColor("#2D3748")

    title_style = ParagraphStyle(
        "DocTitle",
        parent=styles["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=24,
        leading=28,
        textColor=primary_color,
        spaceAfter=6
    )

    subtitle_style = ParagraphStyle(
        "DocSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=11,
        leading=14,
        textColor=colors.HexColor("#718096"),
        spaceAfter=14
    )

    h1_style = ParagraphStyle(
        "SectionH1",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=15,
        leading=18,
        textColor=secondary_color,
        spaceBefore=14,
        spaceAfter=6,
        keepWithNext=True
    )

    h2_style = ParagraphStyle(
        "SectionH2",
        parent=styles["Heading3"],
        fontName="Helvetica-Bold",
        fontSize=12,
        leading=15,
        textColor=primary_color,
        spaceBefore=10,
        spaceAfter=4,
        keepWithNext=True
    )

    body_style = ParagraphStyle(
        "DocBody",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        leading=14,
        textColor=text_color,
        spaceAfter=6
    )

    bullet_style = ParagraphStyle(
        "DocBullet",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=10,
        leading=14,
        textColor=text_color,
        leftIndent=16,
        spaceAfter=4
    )

    callout_style = ParagraphStyle(
        "DocCallout",
        parent=styles["Normal"],
        fontName="Helvetica-Oblique",
        fontSize=9.5,
        leading=13.5,
        textColor=colors.HexColor("#2C5282")
    )

    story = []

    # Title & Metadata Banner
    clean_topic = topic.strip().title()
    story.append(Paragraph(f"Study Guide: {clean_topic}", title_style))
    date_str = datetime.now().strftime("%B %d, %Y")
    story.append(Paragraph(f"Comprehensive Notes &amp; Exam Prep • {date_str}", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1.5, color=secondary_color, spaceBefore=0, spaceAfter=14))

    # Parse markdown content line by line
    lines = markdown_content.split("\n")
    in_callout_buffer = []

    def flush_callout():
        if in_callout_buffer:
            callout_text = "<br/>".join(in_callout_buffer)
            p = Paragraph(callout_text, callout_style)
            tbl = Table([[p]], colWidths=[doc.width])
            tbl.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#EBF8FF")),
                ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#BEE3F8")),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ("LEFTPADDING", (0, 0), (-1, -1), 12),
                ("RIGHTPADDING", (0, 0), (-1, -1), 12),
            ]))
            story.append(tbl)
            story.append(Spacer(1, 8))
            in_callout_buffer.clear()

    def _make_safe_paragraph(text: str, style):
        try:
            return Paragraph(text, style)
        except Exception:
            plain = re.sub(r"<[^>]+>", "", text)
            plain = plain.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            return Paragraph(plain, style)

    in_system_design = False
    for line in lines:
        stripped = line.strip()
        if not stripped:
            flush_callout()
            continue

        # System Design Block
        if "[SYSTEM_DESIGN:" in stripped or stripped.startswith("[SYSTEM_DESIGN:"):
            flush_callout()
            if diagram_image_path and Path(diagram_image_path).exists():
                try:
                    story.append(Spacer(1, 8))
                    img = RLImage(str(diagram_image_path), width=doc.width, height=doc.width * 0.52)
                    story.append(img)
                    story.append(Spacer(1, 8))
                except Exception as img_err:
                    pass
            if not stripped.endswith("]"):
                in_system_design = True
            continue

        if in_system_design:
            if "]" in stripped:
                in_system_design = False
            continue

        # Callout blockquote: > text
        if stripped.startswith(">"):
            flush_callout()
            clean_q = _sanitize_for_reportlab(stripped.lstrip("> ").strip())
            in_callout_buffer.append(clean_q)
            continue
        else:
            flush_callout()

        # Heading 1: # or ##
        if stripped.startswith("## "):
            story.append(Spacer(1, 4))
            clean_h = _sanitize_for_reportlab(stripped.lstrip("# ").strip())
            story.append(_make_safe_paragraph(clean_h, h1_style))
        elif stripped.startswith("# "):
            story.append(Spacer(1, 6))
            clean_h = _sanitize_for_reportlab(stripped.lstrip("# ").strip())
            story.append(_make_safe_paragraph(clean_h, h1_style))
        # Heading 2/3: ###
        elif stripped.startswith("### "):
            story.append(Spacer(1, 2))
            clean_h = _sanitize_for_reportlab(stripped.lstrip("# ").strip())
            story.append(_make_safe_paragraph(clean_h, h2_style))
        # Bullet list: - or *
        elif stripped.startswith("- ") or stripped.startswith("* "):
            clean_b = _sanitize_for_reportlab(stripped[2:].strip())
            story.append(_make_safe_paragraph(f"• {clean_b}", bullet_style))
        # Numbered list: 1. or 2.
        elif re.match(r"^\d+\.\s", stripped):
            match = re.match(r"^(\d+)\.\s+(.*)", stripped)
            if match:
                num, item_text = match.groups()
                clean_item = _sanitize_for_reportlab(item_text)
                story.append(_make_safe_paragraph(f"{num}. {clean_item}", bullet_style))
        else:
            clean_p = _sanitize_for_reportlab(stripped)
            story.append(_make_safe_paragraph(clean_p, body_style))

    flush_callout()

    doc.build(story, canvasmaker=NumberedCanvas)
    return str(output_path)
